
import Function.*;
import javax.swing.JOptionPane;
import Classes.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohmoud
 */
public class Catogeries extends javax.swing.JFrame {
  
    /**
     * Creates new form Catogeries
     */
    public Catogeries(){ 
        try {
            initComponents();
            jTable1.setModel((new Function.Category().showAll()));
            this.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            Logger.getLogger(Catogeries.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDump = new javax.swing.JToggleButton();
        btnupdate = new javax.swing.JToggleButton();
        btnadd = new javax.swing.JToggleButton();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        btndelet = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "الفئات", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "المعرف الرقمي للفئه ", "اسم الفئه", "وصف الفئه"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 100, 498, 93));

        btnDump.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDump.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnDump.setText("تفريغ");
        btnDump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDumpActionPerformed(evt);
            }
        });
        jPanel1.add(btnDump, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 40));

        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back...png"))); // NOI18N
        btnupdate.setText("تحديث معلومه");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 348, 200, 40));

        btnadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submit.png"))); // NOI18N
        btnadd.setText("اضافة فئة");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel1.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 284, 200, 40));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 35, 197, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N
        jButton1.setText("بحث");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 28, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("المعرف الرقمي للفئه");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 248, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("اسم الفئه");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 294, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("وصف الفئة");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 335, -1, -1));

        text.setColumns(20);
        text.setRows(5);
        jScrollPane2.setViewportView(text);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 335, 237, -1));

        jTextField1.setEnabled(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 246, 234, 30));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 292, 234, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "اسم الفئة", "وصف الفئة", "الرقم التعريفى للفئه", " " }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        jButton3.setText("رجوع");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 25, -1, 40));

        btndelet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndelet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel1.png"))); // NOI18N
        btndelet.setText("مسح فئة");
        btndelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletActionPerformed(evt);
            }
        });
        jPanel1.add(btndelet, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 409, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDumpActionPerformed
        try {
            // TODO add your handling code here:
            jTextField1.setText("");
            jTextField3.setText("");
            text.setText("");
            jTable1.setModel((new Function.Category().showAll()));
        } catch (SQLException ex) {
            Logger.getLogger(Catogeries.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDumpActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        Function.Category catfunction = new Function.Category();
        Classes.Category ca = new Classes.Category();

        if(!(jTextField3.getText().equals("")&&text.getText().equals(""))){
            try {
                ca.setCategoryId(Integer.parseInt(String.valueOf(jTextField1.getText())));
                ca.setCategoryName(jTextField3.getText());
                ca.setCategoryDiscruption(text.getText());
                catfunction.update(ca);
                JOptionPane.showMessageDialog(rootPane, "Category update secces");
                jTable1.setModel((new Function.Category().showAll()));
            } catch (SQLException ex) {
                Logger.getLogger(Catogeries.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else
        {
           JOptionPane.showMessageDialog(rootPane, "insert category info ");
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        HOME home=new HOME();
        home.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        Function.Category catfunction = new Function.Category();
        Classes.Category ca = new Classes.Category();

        if(!(jTextField3.getText().equals("")&&text.getText().equals(""))){
            try {
                ca.setCategoryName(jTextField3.getText());
                ca.setCategoryDiscruption(text.getText());
                catfunction.add(ca);
                JOptionPane.showMessageDialog(rootPane, "Category added secces");
                jTable1.setModel((new Function.Category().showAll()));
            } catch (SQLException ex) {
                Logger.getLogger(Catogeries.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else
        {
           JOptionPane.showMessageDialog(rootPane, "insert category info ");
        }

    }//GEN-LAST:event_btnaddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            String colmName = "";
            String keysersh = jTextField2.getText();
            if(jComboBox1.getSelectedItem().equals("اسم الفئة"))
                colmName = "categoryName";
            else if(jComboBox1.getSelectedItem().equals("وصف الفئة"))
                colmName = "categoryDiscruption";
            else if(jComboBox1.getSelectedItem().equals("الرقم التعريفى للفئه"))
                colmName = "categoryId";
            Function.Category cat = new Function.Category();
            if(!(jTextField2.getText().equals("")))
                jTable1.setModel(cat.sersh(keysersh,colmName));
            else
                JOptionPane.showMessageDialog(rootPane, "please Enter wordto searsh");
        } catch (SQLException ex) {
            Logger.getLogger(Catogeries.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            // TODO add your handling code here:
            int row_num = jTable1.getSelectedRow();
            Classes.Category cat = new Classes.Category();
            cat.setCategoryId(Integer.parseInt(String.valueOf(jTable1.getValueAt(row_num, 0))));
            cat = (new Function.Category()).Showrow(cat.getCategoryId());
            jTextField1.setText(String.valueOf(cat.getCategoryId()));
            jTextField3.setText(cat.getCategoryName());
            text.setText(cat.getCategoryDiscruption());
        } catch (SQLException ex) {
            Logger.getLogger(Catogeries.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btndeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletActionPerformed
        // TODO add your handling code here:
        String s = String.valueOf(jTextField1.getText());
        if(!s.equals(""))
        {
            try {
                int id = Integer.parseInt(s);
                (new Function.Category()).delet(id);
                JOptionPane.showMessageDialog(rootPane,"Delet succes");
                btnDumpActionPerformed(evt);
            } catch (SQLException ex) {
                Logger.getLogger(Catogeries.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "selsct category");
        }
                           
    }//GEN-LAST:event_btndeletActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catogeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catogeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catogeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catogeries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catogeries().setVisible(false);
                new Log_In().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDump;
    private javax.swing.JToggleButton btnadd;
    private javax.swing.JToggleButton btndelet;
    private javax.swing.JToggleButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
