/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mohmoud
 */
public class HOME extends javax.swing.JFrame {

    /**
     * Creates new form HOME
     */
    public HOME() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P1 = new javax.swing.JPanel();
        all_cat = new javax.swing.JToggleButton();
        allCustomers = new javax.swing.JToggleButton();
        logout = new javax.swing.JToggleButton();
        sellBooks = new javax.swing.JToggleButton();
        all_author = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        sellBooks1 = new javax.swing.JToggleButton();
        allCustomers1 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        P1.setBackground(new java.awt.Color(0, 0, 0));
        P1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "الصفحة الرئيسية", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        P1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        all_cat.setBackground(new java.awt.Color(0, 51, 51));
        all_cat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        all_cat.setText("الفئات");
        all_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_catActionPerformed(evt);
            }
        });
        P1.add(all_cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 190, 37));

        allCustomers.setBackground(new java.awt.Color(0, 51, 51));
        allCustomers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        allCustomers.setText("الزوار");
        allCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allCustomersActionPerformed(evt);
            }
        });
        P1.add(allCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 190, 36));

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        logout.setText("تسجيل الخروج");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        P1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, 41));

        sellBooks.setBackground(new java.awt.Color(0, 51, 51));
        sellBooks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sellBooks.setText("الكُتب");
        sellBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellBooksActionPerformed(evt);
            }
        });
        P1.add(sellBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 190, 35));

        all_author.setBackground(new java.awt.Color(0, 51, 51));
        all_author.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        all_author.setText("الكُتاب");
        all_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                all_authorActionPerformed(evt);
            }
        });
        P1.add(all_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 190, 37));
        P1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 276, -1, -1));

        sellBooks1.setBackground(new java.awt.Color(0, 0, 0));
        sellBooks1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sellBooks1.setForeground(new java.awt.Color(204, 204, 204));
        sellBooks1.setText("المبيعات");
        sellBooks1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellBooks1ActionPerformed(evt);
            }
        });
        P1.add(sellBooks1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 270, 38));

        allCustomers1.setBackground(new java.awt.Color(0, 51, 51));
        allCustomers1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        allCustomers1.setText("التقارير");
        allCustomers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allCustomers1ActionPerformed(evt);
            }
        });
        P1.add(allCustomers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 190, 36));

        jLabel4.setForeground(new java.awt.Color(51, 0, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LIBRARY11111.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "الصفحه الرئيسية ", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        P1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 830, 530));

        jLabel1.setText("jLabel1");
        P1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        jLabel3.setText("jLabel3");
        P1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        jLabel5.setText("الصفحه الرشيبسبس");
        P1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        jLabel6.setText("jLabel6");
        P1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 523, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void all_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_authorActionPerformed
        // TODO add your handling code here:
        All_Authors authors = new All_Authors();
        authors.setVisible(true);
        dispose();
    }//GEN-LAST:event_all_authorActionPerformed

    private void sellBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellBooksActionPerformed
        // TODO add your handling code here:
        All_Books books=new All_Books();
        books.setVisible(true);
        dispose();

        
        
       
    }//GEN-LAST:event_sellBooksActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Log_In log=new Log_In();
        log.setVisible(true);
        dispose();

    }//GEN-LAST:event_logoutActionPerformed

    private void allCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allCustomersActionPerformed
        // TODO add your handling code here:
        All_Customers customers = new All_Customers();
        customers.setVisible(true);

        dispose();
    }//GEN-LAST:event_allCustomersActionPerformed

    private void all_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_all_catActionPerformed
        // TODO add your handling code here:
        Catogeries cat = new Catogeries();
        cat.setVisible(true);
        dispose();
    }//GEN-LAST:event_all_catActionPerformed

    private void sellBooks1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellBooks1ActionPerformed
        // TODO add your handling code here:
         sell sell = new sell();
        sell.setVisible(true);

        dispose();
        
    }//GEN-LAST:event_sellBooks1ActionPerformed

    private void allCustomers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allCustomers1ActionPerformed
        // TODO add your handling code here:
        Reports report = new Reports();
        report.setVisible(true);

        dispose();
    }//GEN-LAST:event_allCustomers1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(false);
                new Log_In().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P1;
    private javax.swing.JToggleButton allCustomers;
    private javax.swing.JToggleButton allCustomers1;
    private javax.swing.JToggleButton all_author;
    private javax.swing.JToggleButton all_cat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton logout;
    private javax.swing.JToggleButton sellBooks;
    private javax.swing.JToggleButton sellBooks1;
    // End of variables declaration//GEN-END:variables
}
